# Generated by Django 2.0.5 on 2018-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='ocupacao',
            field=models.CharField(choices=[('P', 'proprietario'), ('I', 'inquilino'), ('V', 'vazio')], default='V', max_length=1, verbose_name='Ocupacao'),
        ),
    ]
