# Generated by Django 2.0.5 on 2018-05-30 18:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180530_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='ocupacao',
            field=models.CharField(choices=[('PROPRIETARIO', 'P'), ('INQUILINO', 'I'), ('VAZIO', 'V')], default=core.models.TipoOcupacao('V'), max_length=12, verbose_name='Ocupacao'),
        ),
    ]
